apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: snowflake-ingress
spec:
  ingressClassName: contour
  tls:
    - hosts:
        - snowflake.dev.local
      secretName: snowflake-tls
  rules:
    - host: snowflake.dev.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: snowflake-id-cluster-service
                port:
                  number: 8080
